/:
  controller: main
  action: home

/accueil:
  controller: main
  action: home

/login:
  controller: authentification
  action: login

/register:
  controller: authentification
  action: register

/logout:
  controller: authentification
  action: logout
  security: [Abonne,Admin,Editeur]

/admin:
  controller: main
  action: home
  security: [Admin,Editeur]

/recuperer_mdp:
  controller : user
  action     : recuperer_mdp

/initialiser_mdp/:
  controller : user
  action     : initialiser_mdp
  params: true

/admin/parametre:
  controller: user
  action : parametre
  security: [Admin,Editeur,Abonne]
  params: true

/deletecompte:
   controller: user
   action : deletecompte
   security: [Admin]

/admin/utilisateurs:
   controller: user
   action : index
   security: [Admin,Editeur,Abonne]

/admin/utilisateurs/edit/:
  controller: user
  action: edit
  security: [Admin,Editeur]
  params: true

/admin/utilisateurs/delete/:
  controller: user
  action: delete
  security: [Admin]
  params: true

/admin/category:
  controller: category
  action: index
  security: [Admin,Editeur]

/admin/category/create:
  controller: category
  action: create
  security: [Admin,Editeur,Abonne]

/admin/category/edit/:
  controller: category
  action: edit
  security: [Admin,Editeur,Abonne]
  params: true

/admin/category/delete/:
  controller: category
  action: delete
  security: [Admin,Editeur,Abonne]
  params: true

/admin/forum:
  controller: forum
  action: index
  security: [Admin,Editeur,Abonne]

/admin/forum/create:
  controller: forum
  action: create
  security: [Admin,Editeur,Abonne]

/admin/forum/delete:
  controller: forum
  action: delete
  security: [Admin,Editeur,Abonne]
  params: true

/admin/forum/edit/:
  controller: forum
  action: edit
  security: [Admin,Editeur,Abonne]
  params: true

/forum/detail:
  controller: frontforum
  action: detail
  security: [Admin,Editeur,Abonne]
  params: true

/admin/page:
  controller: page
  action: index
  security: [Admin,Editeur,Abonne]

/admin/page/create:
  controller: page
  action: create
  security: [Admin,Editeur,Abonne]

/admin/page/edit/:
  controller: page
  action: edit
  security: [Admin,Editeur,Abonne]
  params: true

/admin/page/delete:
  controller: page
  action: delete
  security: [Admin,Editeur,Abonne]
  params: true

/admin/event:
  controller: event
  action: index
  security: [Admin,Editeur,Abonne]

/admin/event/create:
  controller: event
  action: create
  security: [Admin,Editeur,Abonne]

/admin/event/delete:
  controller: event
  action: delete
  security: [Admin,Editeur,Abonne]
  params: true

/admin/event/edit/:
  controller: event
  action: edit
  security: [Admin,Editeur,Abonne]
  params: true

/event/detail/:
  controller: frontevent
  action: detail
  security: [Admin,Editeur,Abonne]
  params: true

/admin/manga:
  controller: manga
  action: index
  security: [Admin,Editeur]

/admin/manga/create:
  controller: manga
  action: create
  security: [Admin,Editeur]

/admin/manga/edit/:
  controller: manga
  action: edit
  security: [Admin,Editeur]
  params: true

/admin/manga/delete/:
  controller: manga
  action: delete
  security: [Admin,Editeur]
  params: true

/admin/media:
  controller: media
  action: Allmedia
  security: [Admin,Editeur]
  params: true

/updatepassword:
  controller: user
  action: updatemdp
  params: true

/admin/forumcommentaire:
  controller: forumcommentaire
  action: index
  security: [Admin]

/stripe:
  controller: stripe
  action: stripe

/event:
  controller: frontevent
  action: FrontEvent

/admin/forumcommentaire/edit/:
  controller: forumcommentaire
  action: edit
  security: [Admin]
  params: true

/admin/forumcommentaire/delete/:
  controller: forumcommentaire
  action: delete
  security: [Admin]
  params: true

/manga/detail/:
  controller: frontmanga
  action: detail
  params: true

/createcommentaire/:
  controller: frontforum
  action: create
  security: [Admin,Editeur,Abonne]
  params: true

/admin/template:
  controller: main
  action: Template
  security: [Admin,Editeur,Abonne]

