/:
  controller: main
  action: home
  security: All
  params: null

/nous-contacter:
  controller: main
  action: contact
  security: All
  params: null

/login:
  controller: authentification
  action: login
  security : All
  params: null

/logout:
  controller: authentification
  action: logout
  security: [Abonne,Admin,Editeur]
  params: null

/register:
  controller: authentification
  action: register
  security: All
  params: null

/admin:
  controller: main
  action: home
  security: All
  params: null

/accueil:
  controller: main
  action: home
  security: All
  params: null

/recuperer_mdp:
  controller : user
  action     : recuperer_mdp
  security   : All
  params: null

/initialiser_mdp:
  controller : user
  action     : initialiser_mdp
  security   : All
  params: null

/parametre:
  controller: user
  action : parametre
  security: [Admin,Editeur,Abonne]
  params: null

/deletecompte:
   controller: user
   action : deletecompte
   security: [Admin]
   params: null

/admin/utilisateurs:
   controller: user
   action : index
   security: [Admin,Editeur,Abonne]
   params: null

/admin/utilisateurs/edit/:
  controller: user
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/category:
  controller: category
  action: index
  security: All
  params: null

/deleteCategorie:
  controller: user
  action: deleteCategory
  security: [Admin]
  params: null

/admin/category/edit/:
  controller: category
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/forums:
  controller: forums
  action: create
  security: All
  params: null

/admin/delete:
  controller: forums
  action: delete
  security: All
  params: null

/admin/forum/edit:
  controller: forums
  action: edit
  security: All
  params: id

/admin/forum:
  controller: user
  action: forum
  security: All
  params: null

/admin/manga:
  controller: manga
  action: index
  security: [Admin,Editeur,Abonne]
  params: null

/admin/manga/create:
  controller: manga
  action: create
  security: [Admin,Editeur,Abonne]
  params: null

/admin/manga/edit/:
  controller: manga
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/manga/delete/:
  controller: manga
  action: delete
  security: [Admin]
  params: id

/images:
  controller: user
  action : images
  security: All
  params: null

/media:
    controller: media
    action: Allmedia
    security: All
    params: null

/updatepassword:
  controller: user
  action: updatemdp
  security: All
  params: null

/forumcommentaire:
  controller: forumcommentaire
  action: forumcommentaire
  security: [Admin,Editeur,Abonne]
  params: null
