/:
  controller: main
  action: home
  security: All
  params: null

/nous-contacter:
  controller: main
  action: contact
  security: All
  params: null

/login:
  controller: authentification
  action: login
  security : All
  params: null

/logout:
  controller: authentification
  action: logout
  security: [Abonne,Admin,Editeur]
  params: null

/register:
  controller: authentification
  action: register
  security: All
  params: null

/admin:
  controller: main
  action: home
  security: All
  params: null

/accueil:
  controller: main
  action: home
  security: All
  params: null

/recuperer_mdp:
  controller : user
  action     : recuperer_mdp
  security   : All
  params: null

/initialiser_mdp:
  controller : user
  action     : initialiser_mdp
  security   : All
  params: null

/admin/parametre:
  controller: user
  action : parametre
  security: [Admin,Editeur,Abonne]
  params: null

/deletecompte:
   controller: user
   action : deletecompte
   security: [Admin]
   params: null

/admin/utilisateurs:
   controller: user
   action : index
   security: [Admin,Editeur,Abonne]
   params: null

/admin/utilisateurs/edit/:
  controller: user
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/category:
  controller: category
  action: index
  security: All
  params: null

/admin/category/edit/:
  controller: category
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/category/delete/:
  controller: category
  action: delete
  security: [Admin,Editeur,Abonne]
  params: id


/admin/forum:
  controller: forum
  action: index
  security: [Admin,Editeur,Abonne]
  params: null

/admin/forum/create:
  controller: forum
  action: create
  security: [Admin,Editeur,Abonne]
  params: null

/admin/forum/delete:
  controller: forum
  action: delete
  security: [Admin,Editeur,Abonne]
  params: id

/admin/forum/edit/:
  controller: forum
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/forum/detail:
  controller: frontforum
  action: detail
  security: [Admin,Editeur,Abonne]
  params: id

/admin/page:
  controller: page
  action: index
  security: [Admin,Editeur,Abonne]
  params: null

/admin/page/create:
  controller: page
  action: create
  security: [Admin,Editeur,Abonne]
  params: null

/admin/page/edit/:
  controller: page
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

/admin/page/delete:
  controller: page
  action: delete
  security: [Admin,Editeur,Abonne]
  params: id

/admin/event:
  controller: event
  action: index
  security: [Admin,Editeur,Abonne]
  params: null

/admin/event/create:
  controller: event
  action: create
  security: [Admin,Editeur,Abonne]
  params: null

/admin/event/delete:
  controller: event
  action: delete
  security: [Admin,Editeur,Abonne]
  params: id

/admin/event/edit/:
  controller: event
  action: edit
  security: [Admin,Editeur,Abonne]
  params: id

event/detail/:
  controller: frontevent
  action: detail
  security: [Admin,Editeur,Abonne]
  params: id

/admin/manga:
  controller: manga
  action: index
  security: [Admin,Editeur]
  params: null

/admin/manga/create:
  controller: manga
  action: create
  security: [Admin,Editeur]
  params: null

/admin/manga/edit/:
  controller: manga
  action: edit
  security: [Admin,Editeur]
  params: id

/admin/manga/delete/:
  controller: manga
  action: delete
  security: [Admin,Editeur]
  params: id

/images:
  controller: user
  action : images
  security: All
  params: null

/admin/media:
    controller: media
    action: Allmedia
    security: All
    params: dossier

/updatepassword:
  controller: user
  action: updatemdp
  security: All
  params: email

/admin/forumcommentaire:
  controller: forumcommentaire
  action: index
  security: [Admin]
  params: null

/stripe:
  controller: stripe
  action: stripe
  security: All
  params: null

/event:
  controller: frontevent
  action: FrontEvent
  security: All
  params: null
  
/admin/forumcommentaire/edit/:
  controller: forumcommentaire
  action: edit
  security: [Admin]
  params: id

/admin/forumcommentaire/delete/:
  controller: forumcommentaire
  action: delete
  security: [Admin]
  params: id

/manga:
  controller: manga
  action: index
  security: All
  params: null

/manga/detail/:
  controller: manga
  action: detail
  security: All
  params: id

/evenetzagaz-test:
  controller: frontevent
  action: FrontEvent
  security: All
  params: null

/forum-fafzafaz:
  controller: frontforum
  action: FrontForum
  security: All
  params: null
