/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/eventRegister:
  controller: event
  action: eventRegister

/dashboard:
  controller: admin
  action: home
  security: true

/accueil:
  controller: main
  action: home

/categorie:
  controller: user
  action: category