/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: home
  security: true

/accueil:
  controller: main
  action: home


/parametre:
  controller: user
  action : parametre

/deletecompte:
   controller: user
   action : deletecompte

/utilisateurs:
   controller: admin
   action : utilisateurs

/utilisateurs/update:
  controller: admin
  action: utilisateurs_update

/categorie:
  controller: user
  action: category

/deleteCategorie:
  controller: user
  action: deleteCategory

/editCategorie:
  controller: user
  action: editCategory

/forums:
  controller: user
  action: forums

/deleteForum:
  controller: user
  action: deleteForum

/editForum:
  controller: user
  action: editForum

/forum:
  controller: user
  action: forum

/manga:
  controller: user
  action: manga

/editManga:
  controller: user
  action: editManga

/deleteManga:
  controller: user
  action: deleteManga
