/:
  controller: main
  action: home
  security: All

/nous-contacter:
  controller: main
  action: contact
  security: All

/login:
  controller: user
  action: login
  security: All

/logout:
  controller: user
  action: logout
  security: [Abonne, Admin, Editeur]

/register:
  controller: user
  action: register
  security: All

/event:
  controller: event
  action: event
  security: All

/eventEdit:
  controller: event
  action: editEvent
  security: All

/deleteEvent:
  controller: user
  action: deleteEvent
  security: All

/dashboard:
  controller: admin
  action: home
  security: All

/accueil:
  controller: main
  action: home
  security: All

/recuperer_mdp:
  controller: user
  action: recuperer_mdp
  security: All

/initialiser_mdp:
  controller: user
  action: initialiser_mdp
  security: All

/parametre:
  controller: user
  action: parametre
  security: [Admin, Editeur, Abonne]

/deletecompte:
  controller: user
  action: deletecompte
  security: [Admin]

/utilisateurs:
  controller: admin
  action: utilisateurs
  security: [Admin, Editeur, Abonne]

/utilisateurs/update:
  controller: admin
  action: utilisateurs_update
  security: [Admin, Editeur, Abonne]

/categorie:
  controller: user
  action: category
  security: All

/deleteCategorie:
  controller: user
  action: deleteCategory
  security: [Admin]

/editCategorie:
  controller: user
  action: editCategory
  security: All

/forums:
  controller: user
  action: forums
  security: [Admin, Editeur, Abonne]

/deleteForum:
  controller: user
  action: deleteForum
  security: [Admin]

/editForum:
  controller: user
  action: editForum
  security: All

/forum:
  controller: user
  action: forum
  security: [Admin, Editeur, Abonne]

/manga:
  controller: manga
  action: manga
  security: [Admin, Editeur, Abonne]

/editManga:
  controller: manga
  action: editManga
  security: [Admin, Editeur, Abonne]

/deleteManga:
  controller: manga
  action: deleteManga
  security: [Admin]

/images:
  controller: user
  action: images
  security: All

/media:
  controller: media
  action: Allmedia
  security: [Admin, Editeur, Abonne]

/updatepassword:
  controller: user
  action: updatemdp
  security: [Admin, Editeur, Abonne]
